# Generated by Django 4.1 on 2023-12-13 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '987654321'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('monthly_salary', models.IntegerField()),
                ('approved_limit', models.BigIntegerField()),
                ('current_debt', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('loan_amount', models.BigIntegerField()),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.IntegerField(verbose_name='monthly repayment (emi)')),
                ('emis_paid_on_time', models.IntegerField(verbose_name='EMIs paid on time')),
                ('start_date', models.DateField(verbose_name='Date of Approval')),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.customer')),
            ],
        ),
    ]
