# Generated by Django 4.1 on 2023-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_remove_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
