# Generated by Django 4.1 on 2023-12-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_remove_loan_customer_loan_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer_id',
        ),
    ]
