# Generated by Django 4.1 on 2023-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_remove_loan_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
