# Generated by Django 4.1 on 2023-12-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_loan_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
    ]
