# Generated by Django 4.1 on 2023-12-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_remove_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
